[target.'cfg(target_arch = "x86_64")']
runner = "bootimage runner"

[target.'cfg(target_arch = "aarch64")']
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a76 -kernel"

[build]
target = "x86_64-unknown-none"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]